[project]
name = "instore"
version = "0.0.1"
requires-python = ">= 3.10"
readme = "README.md"

[tool.black]
line-length = 100

[tool.isort]
line_length = 100
include_trailing_comma = true

[tool.pyright]
reportMissingTypeArgument = true
strictListInference = true
include = ["pkg"]
extraPaths = ["."]

[tool.pylint]
disable = [
	"C0114", # Module docstring
	"C0115", # Module class docstring
	"C0116", # Function or method docstring
	"R0903"  # Too few public methods
]
max-line-length = 100
ignore = ["migrations", "tests"]

[tool.setuptools.packages.find]
where = ["."]
include = ["pkg"]
