from typing import Annotated, Any

from langchain_core.tools import BaseTool


class AnalyticsTool(BaseTool):
    name: str = "AnalyticsTool"
    description: str = (
        """Contains information on : 
            - video IDs 
            - where videos are hosted for deletion or movement requests 
            - video sizes
            - usage patterns and latency
            - cost for cold, hot, and cache storage per gb in euros."""
    )

    environment: str = "1"

    all_environments: dict[str, Any] = {
        "1": {
            "costs_euro_per_gb_per_month": {"cache": 0.25, "origin_hot": 0.10, "origin_cold": 0.01},
            "avg_latency_ms": {"EU_ORIGIN_HOT": 500, "EU_ORIGIN_COLD": 2000},
            "videos": {
                "video876": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 2.5,
                    "requests_in_last_hour": {"EU_ORIGIN_HOT": 18, "EU_ORIGIN_COLD": 5},
                    "requests_in_last_day": {"EU_ORIGIN_HOT": 70, "EU_ORIGIN_COLD": 15},
                    "requests_in_last_week": {"EU_ORIGIN_HOT": 280, "EU_ORIGIN_COLD": 60},
                    "requests_in_last_month": {"EU_ORIGIN_HOT": 1100, "EU_ORIGIN_COLD": 250},
                },
                "video123": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 0.9,
                    "requests_in_last_hour": {"EU_ORIGIN_HOT": 25, "EU_ORIGIN_COLD": 12},
                    "requests_in_last_day": {"EU_ORIGIN_HOT": 90, "EU_ORIGIN_COLD": 40},
                    "requests_in_last_week": {"EU_ORIGIN_HOT": 350, "EU_ORIGIN_COLD": 150},
                    "requests_in_last_month": {"EU_ORIGIN_HOT": 1400, "EU_ORIGIN_COLD": 600},
                },
                "video456": {
                    "location": "EU_ORIGIN_COLD",
                    "size_gb": 4.1,
                    "requests_in_last_hour": {"EU_ORIGIN_HOT": 8, "EU_ORIGIN_COLD": 2},
                    "requests_in_last_day": {"EU_ORIGIN_HOT": 30, "EU_ORIGIN_COLD": 7},
                    "requests_in_last_week": {"EU_ORIGIN_HOT": 120, "EU_ORIGIN_COLD": 25},
                    "requests_in_last_month": {"EU_ORIGIN_HOT": 450, "EU_ORIGIN_COLD": 100},
                },
                "video789": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 1.3,
                    "requests_in_last_hour": {"EU_ORIGIN_HOT": 15, "EU_ORIGIN_COLD": 7},
                    "requests_in_last_day": {"EU_ORIGIN_HOT": 60, "EU_ORIGIN_COLD": 20},
                    "requests_in_last_week": {"EU_ORIGIN_HOT": 230, "EU_ORIGIN_COLD": 80},
                    "requests_in_last_month": {"EU_ORIGIN_HOT": 900, "EU_ORIGIN_COLD": 320},
                },
                "video012": {
                    "location": "EU_ORIGIN_COLD",
                    "size_gb": 3.7,
                    "requests_in_last_hour": {"EU_ORIGIN_HOT": 10, "EU_ORIGIN_COLD": 3},
                    "requests_in_last_day": {"EU_ORIGIN_HOT": 40, "EU_ORIGIN_COLD": 10},
                    "requests_in_last_week": {"EU_ORIGIN_HOT": 160, "EU_ORIGIN_COLD": 35},
                    "requests_in_last_month": {"EU_ORIGIN_HOT": 600, "EU_ORIGIN_COLD": 140},
                },
            },
        },
        "2": {
            "costs_euro_per_gb_per_month": {"cache": 0.25, "origin_hot": 0.10, "origin_cold": 0.01},
            "avg_latency_ms": {"EU_BERLIN_CACHE_1": 80, "EU_ORIGIN_HOT": 500, "EU_ORIGIN_COLD": 2000},
            "videos": {
                "video102": {
                    "location": "EU_BERLIN_CACHE_1",
                    "size_gb": 2.3,
                    "requests_in_last_hour": {
                        "EU_BERLIN_CACHE_1": 15,
                        "EU_ORIGIN_HOT": 10,
                        "EU_ORIGIN_COLD": 3,
                    },
                    "requests_in_last_day": {
                        "EU_BERLIN_CACHE_1": 70,
                        "EU_ORIGIN_HOT": 40,
                        "EU_ORIGIN_COLD": 12,
                    },
                    "requests_in_last_week": {
                        "EU_BERLIN_CACHE_1": 280,
                        "EU_ORIGIN_HOT": 150,
                        "EU_ORIGIN_COLD": 50,
                    },
                    "requests_in_last_month": {
                        "EU_BERLIN_CACHE_1": 1100,
                        "EU_ORIGIN_HOT": 600,
                        "EU_ORIGIN_COLD": 200,
                    },
                },
                "video345": {
                    "location": "EU_BERLIN_CACHE_1",
                    "size_gb": 0.7,
                    "requests_in_last_hour": {
                        "EU_BERLIN_CACHE_1": 20,
                        "EU_ORIGIN_HOT": 8,
                        "EU_ORIGIN_COLD": 2,
                    },
                    "requests_in_last_day": {
                        "EU_BERLIN_CACHE_1": 90,
                        "EU_ORIGIN_HOT": 30,
                        "EU_ORIGIN_COLD": 8,
                    },
                    "requests_in_last_week": {
                        "EU_BERLIN_CACHE_1": 350,
                        "EU_ORIGIN_HOT": 110,
                        "EU_ORIGIN_COLD": 35,
                    },
                    "requests_in_last_month": {
                        "EU_BERLIN_CACHE_1": 1400,
                        "EU_ORIGIN_HOT": 450,
                        "EU_ORIGIN_COLD": 130,
                    },
                },
                "video678": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 4.5,
                    "requests_in_last_hour": {
                        "EU_BERLIN_CACHE_1": 8,
                        "EU_ORIGIN_HOT": 18,
                        "EU_ORIGIN_COLD": 6,
                    },
                    "requests_in_last_day": {
                        "EU_BERLIN_CACHE_1": 35,
                        "EU_ORIGIN_HOT": 70,
                        "EU_ORIGIN_COLD": 25,
                    },
                    "requests_in_last_week": {
                        "EU_BERLIN_CACHE_1": 140,
                        "EU_ORIGIN_HOT": 280,
                        "EU_ORIGIN_COLD": 100,
                    },
                    "requests_in_last_month": {
                        "EU_BERLIN_CACHE_1": 550,
                        "EU_ORIGIN_HOT": 1100,
                        "EU_ORIGIN_COLD": 400,
                    },
                },
                "video999": {
                    "location": "EU_BERLIN_CACHE_1",
                    "size_gb": 1.1,
                    "requests_in_last_hour": {
                        "EU_BERLIN_CACHE_1": 12,
                        "EU_ORIGIN_HOT": 5,
                        "EU_ORIGIN_COLD": 1,
                    },
                    "requests_in_last_day": {
                        "EU_BERLIN_CACHE_1": 50,
                        "EU_ORIGIN_HOT": 20,
                        "EU_ORIGIN_COLD": 5,
                    },
                    "requests_in_last_week": {
                        "EU_BERLIN_CACHE_1": 200,
                        "EU_ORIGIN_HOT": 75,
                        "EU_ORIGIN_COLD": 18,
                    },
                    "requests_in_last_month": {
                        "EU_BERLIN_CACHE_1": 800,
                        "EU_ORIGIN_HOT": 300,
                        "EU_ORIGIN_COLD": 70,
                    },
                },
            },
        },
        "3": {
            "costs_euro_per_gb_per_month": {"cache": 0.25, "origin_hot": 0.10, "origin_cold": 0.01},
            "avg_latency_ms": {
                "EU_DUBLIN_CACHE_1": 40,
                "EU_BERLIN_CACHE_1": 80,
                "EU_ORIGIN_HOT": 500,
                "EU_ORIGIN_COLD": 2000,
            },
            "videos": {
                "video921": {
                    "location": "EU_DUBLIN_CACHE_1",
                    "size_gb": 1.8,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 10,
                        "EU_BERLIN_CACHE_1": 8,
                        "EU_ORIGIN_HOT": 15,
                        "EU_ORIGIN_COLD": 3,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 80,
                        "EU_BERLIN_CACHE_1": 60,
                        "EU_ORIGIN_HOT": 50,
                        "EU_ORIGIN_COLD": 10,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 350,
                        "EU_BERLIN_CACHE_1": 280,
                        "EU_ORIGIN_HOT": 180,
                        "EU_ORIGIN_COLD": 40,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 1400,
                        "EU_BERLIN_CACHE_1": 1100,
                        "EU_ORIGIN_HOT": 700,
                        "EU_ORIGIN_COLD": 150,
                    },
                },
                "video345": {
                    "location": "EU_BERLIN_CACHE_1",
                    "size_gb": 0.6,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 2,
                        "EU_BERLIN_CACHE_1": 15,
                        "EU_ORIGIN_HOT": 20,
                        "EU_ORIGIN_COLD": 8,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 15,
                        "EU_BERLIN_CACHE_1": 90,
                        "EU_ORIGIN_HOT": 75,
                        "EU_ORIGIN_COLD": 30,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 60,
                        "EU_BERLIN_CACHE_1": 380,
                        "EU_ORIGIN_HOT": 280,
                        "EU_ORIGIN_COLD": 100,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 250,
                        "EU_BERLIN_CACHE_1": 1500,
                        "EU_ORIGIN_HOT": 1100,
                        "EU_ORIGIN_COLD": 400,
                    },
                },
                "video678": {
                    "location": "EU_DUBLIN_CACHE_1",
                    "size_gb": 4.2,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 25,
                        "EU_BERLIN_CACHE_1": 12,
                        "EU_ORIGIN_HOT": 5,
                        "EU_ORIGIN_COLD": 1,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 180,
                        "EU_BERLIN_CACHE_1": 80,
                        "EU_ORIGIN_HOT": 20,
                        "EU_ORIGIN_COLD": 5,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 750,
                        "EU_BERLIN_CACHE_1": 350,
                        "EU_ORIGIN_HOT": 80,
                        "EU_ORIGIN_COLD": 15,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 2900,
                        "EU_BERLIN_CACHE_1": 1400,
                        "EU_ORIGIN_HOT": 300,
                        "EU_ORIGIN_COLD": 60,
                    },
                },
                "video001": {
                    "location": "EU_DUBLIN_CACHE_1",
                    "size_gb": 2.1,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 12,
                        "EU_BERLIN_CACHE_1": 6,
                        "EU_ORIGIN_HOT": 10,
                        "EU_ORIGIN_COLD": 2,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 90,
                        "EU_BERLIN_CACHE_1": 45,
                        "EU_ORIGIN_HOT": 35,
                        "EU_ORIGIN_COLD": 8,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 400,
                        "EU_BERLIN_CACHE_1": 200,
                        "EU_ORIGIN_HOT": 130,
                        "EU_ORIGIN_COLD": 30,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 1600,
                        "EU_BERLIN_CACHE_1": 800,
                        "EU_ORIGIN_HOT": 500,
                        "EU_ORIGIN_COLD": 120,
                    },
                },
                "video555": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 0.9,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 5,
                        "EU_BERLIN_CACHE_1": 10,
                        "EU_ORIGIN_HOT": 18,
                        "EU_ORIGIN_COLD": 6,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 30,
                        "EU_BERLIN_CACHE_1": 60,
                        "EU_ORIGIN_HOT": 65,
                        "EU_ORIGIN_COLD": 25,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 120,
                        "EU_BERLIN_CACHE_1": 250,
                        "EU_ORIGIN_HOT": 250,
                        "EU_ORIGIN_COLD": 90,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 500,
                        "EU_BERLIN_CACHE_1": 1000,
                        "EU_ORIGIN_HOT": 950,
                        "EU_ORIGIN_COLD": 350,
                    },
                },
            },
        },
        "4": {
            "costs_euro_per_gb_per_month": {"cache": 0.25, "origin_hot": 0.10, "origin_cold": 0.01},
            "avg_latency_ms": {
                "EU_DUBLIN_CACHE_1": 40,
                "EU_BERLIN_CACHE_1": 80,
                "EU_PARIS_CACHE_1": 60,
                "EU_ORIGIN_HOT": 500,
                "EU_ORIGIN_COLD": 2000,
            },
            "videos": {
                "video876": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 1.9,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 12,
                        "EU_BERLIN_CACHE_1": 8,
                        "EU_PARIS_CACHE_1": 10,
                        "EU_ORIGIN_HOT": 18,
                        "EU_ORIGIN_COLD": 5,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 70,
                        "EU_BERLIN_CACHE_1": 60,
                        "EU_PARIS_CACHE_1": 75,
                        "EU_ORIGIN_HOT": 60,
                        "EU_ORIGIN_COLD": 15,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 300,
                        "EU_BERLIN_CACHE_1": 250,
                        "EU_PARIS_CACHE_1": 320,
                        "EU_ORIGIN_HOT": 220,
                        "EU_ORIGIN_COLD": 50,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 1200,
                        "EU_BERLIN_CACHE_1": 1000,
                        "EU_PARIS_CACHE_1": 1300,
                        "EU_ORIGIN_HOT": 850,
                        "EU_ORIGIN_COLD": 180,
                    },
                },
                "video123": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 0.8,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 4,
                        "EU_BERLIN_CACHE_1": 15,
                        "EU_PARIS_CACHE_1": 12,
                        "EU_ORIGIN_HOT": 25,
                        "EU_ORIGIN_COLD": 10,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 25,
                        "EU_BERLIN_CACHE_1": 90,
                        "EU_PARIS_CACHE_1": 70,
                        "EU_ORIGIN_HOT": 90,
                        "EU_ORIGIN_COLD": 40,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 100,
                        "EU_BERLIN_CACHE_1": 380,
                        "EU_PARIS_CACHE_1": 280,
                        "EU_ORIGIN_HOT": 350,
                        "EU_ORIGIN_COLD": 130,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 400,
                        "EU_BERLIN_CACHE_1": 1500,
                        "EU_PARIS_CACHE_1": 1100,
                        "EU_ORIGIN_HOT": 1400,
                        "EU_ORIGIN_COLD": 500,
                    },
                },
                "video456": {
                    "location": "EU_DUBLIN_CACHE_1",
                    "size_gb": 4.1,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 20,
                        "EU_BERLIN_CACHE_1": 10,
                        "EU_PARIS_CACHE_1": 7,
                        "EU_ORIGIN_HOT": 5,
                        "EU_ORIGIN_COLD": 1,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 140,
                        "EU_BERLIN_CACHE_1": 70,
                        "EU_PARIS_CACHE_1": 50,
                        "EU_ORIGIN_HOT": 20,
                        "EU_ORIGIN_COLD": 5,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 580,
                        "EU_BERLIN_CACHE_1": 280,
                        "EU_PARIS_CACHE_1": 200,
                        "EU_ORIGIN_HOT": 75,
                        "EU_ORIGIN_COLD": 15,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 2300,
                        "EU_BERLIN_CACHE_1": 1100,
                        "EU_PARIS_CACHE_1": 800,
                        "EU_ORIGIN_HOT": 300,
                        "EU_ORIGIN_COLD": 60,
                    },
                },
                "video789": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 1.4,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 10,
                        "EU_BERLIN_CACHE_1": 6,
                        "EU_PARIS_CACHE_1": 8,
                        "EU_ORIGIN_HOT": 15,
                        "EU_ORIGIN_COLD": 4,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 60,
                        "EU_BERLIN_CACHE_1": 35,
                        "EU_PARIS_CACHE_1": 45,
                        "EU_ORIGIN_HOT": 55,
                        "EU_ORIGIN_COLD": 12,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 240,
                        "EU_BERLIN_CACHE_1": 140,
                        "EU_PARIS_CACHE_1": 180,
                        "EU_ORIGIN_HOT": 200,
                        "EU_ORIGIN_COLD": 48,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 950,
                        "EU_BERLIN_CACHE_1": 550,
                        "EU_PARIS_CACHE_1": 700,
                        "EU_ORIGIN_HOT": 800,
                        "EU_ORIGIN_COLD": 190,
                    },
                },
            },
        },
        "5": {
            "costs_euro_per_gb_per_month": {"cache": 0.25, "origin_hot": 0.10, "origin_cold": 0.01},
            "avg_latency_ms": {
                "EU_BERLIN_CACHE_1": 80,
                "EU_ORIGIN_HOT": 500,
                "EU_ORIGIN_COLD": 2000,
                "US_ORIGIN_HOT": 1000,
                "US_ORIGIN_COLD": 4000,
            },
            "videos": {
                "video876": {
                    "location": "US_ORIGIN_HOT",
                    "size_gb": 2.0,
                    "requests_in_last_hour": {
                        "EU_BERLIN_CACHE_1": 15,
                        "EU_ORIGIN_HOT": 20,
                        "EU_ORIGIN_COLD": 6,
                        "US_ORIGIN_HOT": 22,
                        "US_ORIGIN_COLD": 4,
                    },
                    "requests_in_last_day": {
                        "EU_BERLIN_CACHE_1": 70,
                        "EU_ORIGIN_HOT": 75,
                        "EU_ORIGIN_COLD": 18,
                        "US_ORIGIN_HOT": 80,
                        "US_ORIGIN_COLD": 10,
                    },
                    "requests_in_last_week": {
                        "EU_BERLIN_CACHE_1": 300,
                        "EU_ORIGIN_HOT": 290,
                        "EU_ORIGIN_COLD": 65,
                        "US_ORIGIN_HOT": 320,
                        "US_ORIGIN_COLD": 30,
                    },
                    "requests_in_last_month": {
                        "EU_BERLIN_CACHE_1": 1200,
                        "EU_ORIGIN_HOT": 1150,
                        "EU_ORIGIN_COLD": 260,
                        "US_ORIGIN_HOT": 1300,
                        "US_ORIGIN_COLD": 120,
                    },
                },
                "video123": {
                    "location": "EU_BERLIN_CACHE_1",
                    "size_gb": 0.9,
                    "requests_in_last_hour": {
                        "EU_BERLIN_CACHE_1": 22,
                        "EU_ORIGIN_HOT": 10,
                        "EU_ORIGIN_COLD": 3,
                        "US_ORIGIN_HOT": 12,
                        "US_ORIGIN_COLD": 5,
                    },
                    "requests_in_last_day": {
                        "EU_BERLIN_CACHE_1": 95,
                        "EU_ORIGIN_HOT": 40,
                        "EU_ORIGIN_COLD": 10,
                        "US_ORIGIN_HOT": 50,
                        "US_ORIGIN_COLD": 18,
                    },
                    "requests_in_last_week": {
                        "EU_BERLIN_CACHE_1": 400,
                        "EU_ORIGIN_HOT": 150,
                        "EU_ORIGIN_COLD": 35,
                        "US_ORIGIN_HOT": 200,
                        "US_ORIGIN_COLD": 70,
                    },
                    "requests_in_last_month": {
                        "EU_BERLIN_CACHE_1": 1600,
                        "EU_ORIGIN_HOT": 600,
                        "EU_ORIGIN_COLD": 140,
                        "US_ORIGIN_HOT": 800,
                        "US_ORIGIN_COLD": 280,
                    },
                },
                "video456": {
                    "location": "EU_BERLIN_CACHE_1",
                    "size_gb": 4.3,
                    "requests_in_last_hour": {
                        "EU_BERLIN_CACHE_1": 10,
                        "EU_ORIGIN_HOT": 6,
                        "EU_ORIGIN_COLD": 1,
                        "US_ORIGIN_HOT": 8,
                        "US_ORIGIN_COLD": 2,
                    },
                    "requests_in_last_day": {
                        "EU_BERLIN_CACHE_1": 50,
                        "EU_ORIGIN_HOT": 25,
                        "EU_ORIGIN_COLD": 5,
                        "US_ORIGIN_HOT": 30,
                        "US_ORIGIN_COLD": 7,
                    },
                    "requests_in_last_week": {
                        "EU_BERLIN_CACHE_1": 200,
                        "EU_ORIGIN_HOT": 90,
                        "EU_ORIGIN_COLD": 15,
                        "US_ORIGIN_HOT": 110,
                        "US_ORIGIN_COLD": 20,
                    },
                    "requests_in_last_month": {
                        "EU_BERLIN_CACHE_1": 800,
                        "EU_ORIGIN_HOT": 350,
                        "EU_ORIGIN_COLD": 60,
                        "US_ORIGIN_HOT": 450,
                        "US_ORIGIN_COLD": 80,
                    },
                },
                "video789": {
                    "location": "US_ORIGIN_HOT",
                    "size_gb": 1.6,
                    "requests_in_last_hour": {
                        "EU_BERLIN_CACHE_1": 12,
                        "EU_ORIGIN_HOT": 18,
                        "EU_ORIGIN_COLD": 5,
                        "US_ORIGIN_HOT": 20,
                        "US_ORIGIN_COLD": 6,
                    },
                    "requests_in_last_day": {
                        "EU_BERLIN_CACHE_1": 60,
                        "EU_ORIGIN_HOT": 70,
                        "EU_ORIGIN_COLD": 15,
                        "US_ORIGIN_HOT": 80,
                        "US_ORIGIN_COLD": 20,
                    },
                    "requests_in_last_week": {
                        "EU_BERLIN_CACHE_1": 250,
                        "EU_ORIGIN_HOT": 280,
                        "EU_ORIGIN_COLD": 55,
                        "US_ORIGIN_HOT": 320,
                        "US_ORIGIN_COLD": 80,
                    },
                    "requests_in_last_month": {
                        "EU_BERLIN_CACHE_1": 1000,
                        "EU_ORIGIN_HOT": 1100,
                        "EU_ORIGIN_COLD": 220,
                        "US_ORIGIN_HOT": 1300,
                        "US_ORIGIN_COLD": 320,
                    },
                },
            },
        },
        "6": {
            "costs_euro_per_gb_per_month": {"cache": 0.28, "origin_hot": 0.12, "origin_cold": 0.015},
            "avg_latency_ms": {
                "EU_DUBLIN_CACHE_1": 45,
                "EU_BERLIN_CACHE_1": 88,
                "EU_ORIGIN_HOT": 530,
                "EU_ORIGIN_COLD": 2100,
            },
            "videos": {
                "video921": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 1.8,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 10,
                        "EU_BERLIN_CACHE_1": 8,
                        "EU_ORIGIN_HOT": 15,
                        "EU_ORIGIN_COLD": 3,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 80,
                        "EU_BERLIN_CACHE_1": 60,
                        "EU_ORIGIN_HOT": 50,
                        "EU_ORIGIN_COLD": 10,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 350,
                        "EU_BERLIN_CACHE_1": 280,
                        "EU_ORIGIN_HOT": 180,
                        "EU_ORIGIN_COLD": 40,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 1400,
                        "EU_BERLIN_CACHE_1": 1100,
                        "EU_ORIGIN_HOT": 700,
                        "EU_ORIGIN_COLD": 150,
                    },
                },
                "video345": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 0.6,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 2,
                        "EU_BERLIN_CACHE_1": 15,
                        "EU_ORIGIN_HOT": 20,
                        "EU_ORIGIN_COLD": 8,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 15,
                        "EU_BERLIN_CACHE_1": 90,
                        "EU_ORIGIN_HOT": 75,
                        "EU_ORIGIN_COLD": 30,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 60,
                        "EU_BERLIN_CACHE_1": 380,
                        "EU_ORIGIN_HOT": 280,
                        "EU_ORIGIN_COLD": 100,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 250,
                        "EU_BERLIN_CACHE_1": 1500,
                        "EU_ORIGIN_HOT": 1100,
                        "EU_ORIGIN_COLD": 400,
                    },
                },
                "video678": {
                    "location": "EU_DUBLIN_CACHE_1",
                    "size_gb": 4.2,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 25,
                        "EU_BERLIN_CACHE_1": 12,
                        "EU_ORIGIN_HOT": 5,
                        "EU_ORIGIN_COLD": 1,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 180,
                        "EU_BERLIN_CACHE_1": 80,
                        "EU_ORIGIN_HOT": 20,
                        "EU_ORIGIN_COLD": 5,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 750,
                        "EU_BERLIN_CACHE_1": 350,
                        "EU_ORIGIN_HOT": 80,
                        "EU_ORIGIN_COLD": 15,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 2900,
                        "EU_BERLIN_CACHE_1": 1400,
                        "EU_ORIGIN_HOT": 300,
                        "EU_ORIGIN_COLD": 60,
                    },
                },
                "video001": {
                    "location": "EU_DUBLIN_CACHE_1",
                    "size_gb": 2.1,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 12,
                        "EU_BERLIN_CACHE_1": 6,
                        "EU_ORIGIN_HOT": 10,
                        "EU_ORIGIN_COLD": 2,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 90,
                        "EU_BERLIN_CACHE_1": 45,
                        "EU_ORIGIN_HOT": 35,
                        "EU_ORIGIN_COLD": 8,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 400,
                        "EU_BERLIN_CACHE_1": 200,
                        "EU_ORIGIN_HOT": 130,
                        "EU_ORIGIN_COLD": 30,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 1600,
                        "EU_BERLIN_CACHE_1": 800,
                        "EU_ORIGIN_HOT": 500,
                        "EU_ORIGIN_COLD": 120,
                    },
                },
                "video555": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 0.9,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 5,
                        "EU_BERLIN_CACHE_1": 10,
                        "EU_ORIGIN_HOT": 18,
                        "EU_ORIGIN_COLD": 6,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 30,
                        "EU_BERLIN_CACHE_1": 60,
                        "EU_ORIGIN_HOT": 65,
                        "EU_ORIGIN_COLD": 25,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 120,
                        "EU_BERLIN_CACHE_1": 250,
                        "EU_ORIGIN_HOT": 250,
                        "EU_ORIGIN_COLD": 90,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 500,
                        "EU_BERLIN_CACHE_1": 1000,
                        "EU_ORIGIN_HOT": 950,
                        "EU_ORIGIN_COLD": 350,
                    },
                },
            },
        },
        "7": {
            "costs_euro_per_gb_per_month": {"cache": 0.26, "origin_hot": 0.11, "origin_cold": 0.012},
            "avg_latency_ms": {
                "EU_DUBLIN_CACHE_1": 43,
                "EU_BERLIN_CACHE_1": 85,
                "EU_PARIS_CACHE_1": 62,
                "EU_ORIGIN_HOT": 520,
                "EU_ORIGIN_COLD": 2050,
            },
            "videos": {
                "video876": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 1.9,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 12,
                        "EU_BERLIN_CACHE_1": 8,
                        "EU_PARIS_CACHE_1": 10,
                        "EU_ORIGIN_HOT": 18,
                        "EU_ORIGIN_COLD": 5,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 70,
                        "EU_BERLIN_CACHE_1": 60,
                        "EU_PARIS_CACHE_1": 75,
                        "EU_ORIGIN_HOT": 60,
                        "EU_ORIGIN_COLD": 15,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 300,
                        "EU_BERLIN_CACHE_1": 250,
                        "EU_PARIS_CACHE_1": 320,
                        "EU_ORIGIN_HOT": 220,
                        "EU_ORIGIN_COLD": 50,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 1200,
                        "EU_BERLIN_CACHE_1": 1000,
                        "EU_PARIS_CACHE_1": 1300,
                        "EU_ORIGIN_HOT": 850,
                        "EU_ORIGIN_COLD": 180,
                    },
                },
                "video123": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 0.8,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 4,
                        "EU_BERLIN_CACHE_1": 15,
                        "EU_PARIS_CACHE_1": 12,
                        "EU_ORIGIN_HOT": 25,
                        "EU_ORIGIN_COLD": 10,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 25,
                        "EU_BERLIN_CACHE_1": 90,
                        "EU_PARIS_CACHE_1": 70,
                        "EU_ORIGIN_HOT": 90,
                        "EU_ORIGIN_COLD": 40,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 100,
                        "EU_BERLIN_CACHE_1": 380,
                        "EU_PARIS_CACHE_1": 280,
                        "EU_ORIGIN_HOT": 350,
                        "EU_ORIGIN_COLD": 130,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 400,
                        "EU_BERLIN_CACHE_1": 1500,
                        "EU_PARIS_CACHE_1": 1100,
                        "EU_ORIGIN_HOT": 1400,
                        "EU_ORIGIN_COLD": 500,
                    },
                },
                "video456": {
                    "location": "EU_DUBLIN_CACHE_1",
                    "size_gb": 4.1,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 20,
                        "EU_BERLIN_CACHE_1": 10,
                        "EU_PARIS_CACHE_1": 7,
                        "EU_ORIGIN_HOT": 5,
                        "EU_ORIGIN_COLD": 1,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 140,
                        "EU_BERLIN_CACHE_1": 70,
                        "EU_PARIS_CACHE_1": 50,
                        "EU_ORIGIN_HOT": 20,
                        "EU_ORIGIN_COLD": 5,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 580,
                        "EU_BERLIN_CACHE_1": 280,
                        "EU_PARIS_CACHE_1": 200,
                        "EU_ORIGIN_HOT": 75,
                        "EU_ORIGIN_COLD": 15,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 2300,
                        "EU_BERLIN_CACHE_1": 1100,
                        "EU_PARIS_CACHE_1": 800,
                        "EU_ORIGIN_HOT": 300,
                        "EU_ORIGIN_COLD": 60,
                    },
                },
                "video789": {
                    "location": "EU_ORIGIN_HOT",
                    "size_gb": 1.4,
                    "requests_in_last_hour": {
                        "EU_DUBLIN_CACHE_1": 10,
                        "EU_BERLIN_CACHE_1": 6,
                        "EU_PARIS_CACHE_1": 8,
                        "EU_ORIGIN_HOT": 15,
                        "EU_ORIGIN_COLD": 4,
                    },
                    "requests_in_last_day": {
                        "EU_DUBLIN_CACHE_1": 60,
                        "EU_BERLIN_CACHE_1": 35,
                        "EU_PARIS_CACHE_1": 45,
                        "EU_ORIGIN_HOT": 55,
                        "EU_ORIGIN_COLD": 12,
                    },
                    "requests_in_last_week": {
                        "EU_DUBLIN_CACHE_1": 240,
                        "EU_BERLIN_CACHE_1": 140,
                        "EU_PARIS_CACHE_1": 180,
                        "EU_ORIGIN_HOT": 200,
                        "EU_ORIGIN_COLD": 48,
                    },
                    "requests_in_last_month": {
                        "EU_DUBLIN_CACHE_1": 950,
                        "EU_BERLIN_CACHE_1": 550,
                        "EU_PARIS_CACHE_1": 700,
                        "EU_ORIGIN_HOT": 800,
                        "EU_ORIGIN_COLD": 190,
                    },
                },
            },
        },
    }

    def _run(self):
        return str(self.all_environments[self.environment])
